config/urls.py
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from apps.core.views.default import handler403, handler404, handler500, IndexPage

from . import api

# URLs that can be seen by Swagger after one has authenticated
public_apis = [
    url(r'^api/v1/', include(api)),
]

# Remove docs from production
schema_view = get_schema_view(
    openapi.Info(
        title="GAS YETU API DOCS",
        default_version='v1',
        description="GAS YETU APIs",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="group.rnd@jambopay.com"),
    ),
    permission_classes=(permissions.AllowAny,),
    public=False,
    patterns=public_apis,
)

docs = [
    url(r'^docs/$', login_required(schema_view.with_ui('swagger',
                                                       cache_timeout=None)), name='schema-swagger-ui'),
]


urlpatterns = public_apis + docs + [
    url(r'^$', IndexPage.as_view(), name='home'),
    url(r'^account/', include('apps.accounts.urls.default', namespace='account')),
    url(r'^account/', include('allauth.urls')),
    url(r'^distribution/', include('apps.distribution.urls.default')),
    url(r'^consumers/', include('apps.consumers.urls.default')),
    url(r'^core/', include('apps.core.urls')),
    url(r'^surveys/', include('apps.surveys.urls.default')),
    url(r'^finance/', include('apps.finance.urls.default', namespace='finance')),
    url(r'^inventory/', include('apps.inventory.urls.default')),
    url(r'^products/', include('apps.products.urls.default')),
    url(r'^orders/', include('apps.orders.urls.default')),
    url(r'^admin/', admin.site.urls),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(r'^accounts/login/$', auth_views.LoginView,
        {'template_name': 'admin/login.html'}),
    url(r'^accounts/logout/$', auth_views.LogoutView),
]

handler403 = handler403
handler404 = handler404
handler500 = handler500

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_SITE_INDEX_TITLE
admin.site.site_title = settings.ADMIN_SITE_SITE_TITLE

apps/surveys/models.py
import json

from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from djgeojson.fields import PointField
from rolepermissions.roles import assign_role

from apps.accounts.choices import PROFILE_TYPES
from apps.consumers.models import Beneficiary, Consumer
from apps.core.models import BaseModel, Location, Region, SubRegion, Village
from apps.core.utils import NullableEmailField
from apps.surveys.choices import (CLOSED_ENDED, MAIN_SOURCE_OF_ENERGY,
                                  MONTHLY_EXPENDITURE, OPEN_ENDED_QUESTIONS)
from apps.tenants.models import Tenant


class Questionnaire(BaseModel):
    title = models.CharField(max_length=100, unique=True)
    pass_mark = models.PositiveSmallIntegerField(default=10)

    def __str__(self):
        return f'{self.title}'


class Question(BaseModel):
    """

    Questions :

    Q1. Predominant wall, closed
    Q2. Predominant roof, closed
    Q3. Main source of energy, open
    Q4. Use of LPG, closed
    Q5. Monthly Expenditure, open
    Q6. Household average income, open


    """

    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)
    question = models.CharField(max_length=512)
    question_type = models.IntegerField(
        choices=OPEN_ENDED_QUESTIONS, default=CLOSED_ENDED)
    question_order = models.PositiveSmallIntegerField(default=0)
    expected_answer_count = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return f'{self.question}'

    @property
    def is_open_ended(self):
        return self.question_type in [MAIN_SOURCE_OF_ENERGY, MONTHLY_EXPENDITURE]

    class Meta:
        unique_together = ('questionnaire', 'question')


class Option(BaseModel):
    option = models.CharField(max_length=512)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    nested_child_question = models.ForeignKey(
        Question, null=True, blank=True, related_name='nested_child_questions', on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.option}'

    class Meta:
        unique_together = ('option', 'question')


class Survey(BaseModel):
    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)
    consumer = models.ForeignKey(
        Consumer, on_delete=models.CASCADE)
    enumerator = models.ForeignKey(
        'surveys.Enumerator', on_delete=models.SET_NULL, null=True, blank=True)
    geom = PointField(null=True, blank=True)

    @property
    def enumerator_name(self):
        return self.enumerator.title

    @property
    def consumer_name(self):
        return self.consumer.user.get_full_name()

    @property
    def consumer_region(self):
        return self.consumer.user.region.title

    def __str__(self):
        return f'{self.consumer} - {self.questionnaire}'

    def get_position(self):
        return json.loads(self.geom)

    def promote_consumer(self):
        beneficiary = Beneficiary(
            user=self.consumer.user, date_approved=timezone.now())
        beneficiary.__dict__.update(self.consumer.__dict__)
        beneficiary.save()
        user = self.consumer.user
        user.profile_type = PROFILE_TYPES.Beneficiary
        user.save()
        assign_role(self.consumer.user, 'beneficiary')

    @property
    def passed(self):
        return self.questionnaire.pass_mark >= self.attempted_count

    @property
    def question_count(self):
        return Question.objects.filter(questionnaire=self.questionnaire).count()

    @property
    def attempted_count(self):
        return Question.objects.filter(selectedoption__survey=self).distinct().count()

    @property
    def correct_answer_count(self):
        correct_close_ended_questions = 0
        correct_open_ended_questions = 0

        close_ended_questions = Question.objects.filter(
            question_type=CLOSED_ENDED, questionnaire=self.questionnaire
        )

        for question in close_ended_questions:
            selected = SelectedOption.objects.filter(
                question=question, survey=self
            ).first()

            if selected:
                if selected.option.is_correct:
                    correct_close_ended_questions += 1

        main_source_of_energy = Question.objects.filter(
            question_type=MAIN_SOURCE_OF_ENERGY, questionnaire=self.questionnaire
        ).first()

        main_source_of_energy_answers = SelectedOption.objects.filter(
            question=main_source_of_energy, survey=self
        )

        kerosene_present = False
        charcoal_present = False
        other_source_present = False

        for answer in main_source_of_energy_answers:

            option = answer.option.option

            if option == 'Kerosene':
                kerosene_present = True
            elif option == 'Charcoal':
                charcoal_present = True
            else:
                other_source_present = True

        # Disqualify the answer if the user uses another different form of
        # energy

        if other_source_present:
            pass
        elif kerosene_present or charcoal_present:
            correct_open_ended_questions += 1

        monthly_expenditure = Question.objects.filter(
            question_type=MONTHLY_EXPENDITURE, questionnaire=self.questionnaire
        )

        monthly_expenditure_answers = SelectedOption.objects.filter(
            question__in=monthly_expenditure, survey=self
        )

        expenditure = 0

        for answer in monthly_expenditure_answers:
            detail = answer.answer
            try:
                detail = int(detail)
            except ValueError:
                detail = 0
            expenditure += detail

        if 25000 < expenditure:
            correct_open_ended_questions += 1

        correct = correct_close_ended_questions + correct_open_ended_questions

        return correct

    class Meta:
        unique_together = ('questionnaire', 'consumer')


class SelectedOption(BaseModel):
    option = models.ForeignKey(Option, on_delete=models.CASCADE)
    answer = models.CharField(max_length=64, null=True, blank=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.option.question} - {self.option}'

    class Meta:
        unique_together = ('option', 'question', 'survey')


class Enumerator(BaseModel):
    """
    Enumerators registered in the system
    """
    enumerator_tenant = models.OneToOneField(
        Tenant, on_delete=models.CASCADE, null=True, related_name='enumerator_tenant')
    title = models.CharField(
        max_length=100, help_text='Name of the Enumarator')
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    identity_number = models.CharField(max_length=20, blank=False)
    phone_number = models.CharField(
        _('phone number'), max_length=16, unique=True, default=None, help_text='Contact Phone Number'
    )
    email_address = NullableEmailField(
        _('e-mail address'), blank=True, null=True, default=None, unique=True,
        help_text='Email Address')
    kra_pin_number = models.CharField(
        max_length=30, help_text='KRA pin number', null=True)
    postal_address = models.CharField(
        max_length=30, help_text='Business postal address', null=True)
    region = models.ForeignKey(
        Region, null=True, blank=True, on_delete=models.SET_NULL)
    sub_region = models.ForeignKey(
        SubRegion, blank=True, null=True, on_delete=models.SET_NULL)
    location = models.ForeignKey(
        Location, null=True, blank=True, on_delete=models.SET_NULL)
    village = models.ForeignKey(
        Village, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return '{}'.format(self.enumerator_tenant)

apps/surveys/forms.py
from django import forms
from django.forms import ModelForm, SelectDateWidget
from django.utils.translation import ugettext as _

from apps.accounts import messages
from apps.accounts.models import User

from .models import Enumerator, Option, Question, Questionnaire


class EnumeratorForm(ModelForm):
    phone_number = forms.RegexField(regex=r'^(07)[0-9]{8}$',
                                    error_messages={
                                        'invalid': messages.phone_format},
                                    required=True)

    class Meta:
        model = Enumerator
        fields = (
            'title',
            'identity_number',
            'phone_number',
            'email_address',
            'kra_pin_number',
            'postal_address',
            'region',
            'sub_region',
            'location',
            'village',
            'start_date',
            'end_date'
        )
        widgets = {
            'end_date': forms.DateInput(format=('%d-%m-%Y'),
                                        attrs={'id': 'endDate',
                                               'placeholder': 'Select a date'}),
            'start_date': forms.DateInput(format=('%d-%m-%Y'),
                                          attrs={'id': 'startDate',
                                                 'placeholder': 'Select a date'})
        }

    def clean_phone_number(self):
        instance = getattr(self, 'instance', None)
        phone_number = self.data.get('phone_number', None)
        if instance.pk is None:
            if phone_number:
                phone_number = '254' + phone_number[-9:]
                if Enumerator.objects.filter(phone_number=phone_number).exists():
                    raise forms.ValidationError(
                        _("Enumerator with this phone number already exists."))
                if User.objects.filter(phone=phone_number).exists():
                    raise forms.ValidationError(
                        _("User with this phone number already exists."))
        return phone_number


class QuestionnaireForm(ModelForm):

    class Meta:
        model = Questionnaire
        fields = (
            'title',
            'pass_mark'
        )


class QuestionForm(ModelForm):

    class Meta:
        model = Question
        fields = (
            'questionnaire',
            'question',
            'question_order'

        )


class OptionForm(ModelForm):

    class Meta:
        model = Option
        fields = (
            'option',
            'is_correct',
            'question'
        )

apps/surveys/views.py
from django.shortcuts import render

# Create your views here.

apps/surveys/views/api.py
from rest_framework import status, viewsets
from rest_framework.response import Response
from rest_framework.settings import api_settings
from rolepermissions.decorators import has_role_decorator
from rolepermissions.mixins import HasRoleMixin

from apps.core.viewsets import ReadOnlyViewSet

from .. import models, serializers


class QuestionnaireViewset(HasRoleMixin, ReadOnlyViewSet):
    queryset = models.Questionnaire.objects.all()
    serializer_class = serializers.QuestionnaireSerializer
    allowed_roles = ['enumerator']

    def get_queryset(self):
        queryset = super(QuestionnaireViewset, self).get_queryset()
        return queryset


class SurveyRespond(HasRoleMixin, viewsets.GenericViewSet):
    serializer_class = serializers.SurveyResponseSerializer
    allowed_roles = ['enumerator']

    def get_success_headers(self, data):
        try:
            return {'Location': str(data[api_settings.URL_FIELD_NAME])}
        except (TypeError, KeyError):
            return {}

    def create(self, request, *args, **kwargs):
        """
        Handles Questionnaire responses with the format
        {
            "questionnaire_id":  "1",
            "identity_number":  "123",
            "respondent_name": "John Doe",
            "spouse_identity_number": "789",
            "spouse_name": "Mary Doe",
            "option_responses":
                [
                    {"question_id" : "1", "option_id": "1"},
                    {"question_id" : "2", "option_id": "1"},
                    {"question_id": "2", "option_id": "4", "user_input": "10,1000,10000"},
                ]
        }
        """

        serializer = self.get_serializer(data=request.data, context={
                                         'request': request})
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

    def perform_create(self, serializer):
        serializer.save()

apps/surveys/templates/surveys/add_question.html
{% extends "page.html" %} {% load static %} {% load permission_tags %} {% load i18n %} {% load widget_tweaks %} 
{% block title %} Add Question{% endblock title %} {% block stylesheets %} {{ block.super }}
<link rel="stylesheet" href="{% static 'css/order.css' %}"> {% endblock stylesheets %} 
{% block page %} {% load crispy_forms_tags %} {% include 'messages.html' %}
<form action="" id="orderForm" data-listings-url="#" novalidate method="post">
    
    {% csrf_token %}
    {{ question_form | crispy }}

    {{ option_formset.management_form|crispy }}
    <fieldset>
        <table class="table">
            {% for form in option_formset %} 
            {% if forloop.first %}
            <thead>
                <tr>
                    {% for field in form.visible_fields %}
                    <th>{{ field.label|capfirst }}</th>
                    {% endfor %}
                </tr>
            </thead>
            {% endif %}
            <tr class="{% cycle "row1" "row2" %} formset_row">
                {% for field in form.visible_fields %}
                <td>
                    {% if forloop.first %} 
                        {% for hidden in form.hidden_fields %} 
                            {{ hidden }} 
                        {% endfor %} 
                    {% endif %} 
                    {{ field.errors.as_ul }} 
                    {{ field }}
                </td>
                {% endfor %}

            </tr>
            {% endfor %}
        </table>
    </fieldset>

    <div class="pull-right">
        <input class="btn btn-link" type="button" value="Cancel" onclick="window.history.go(-1);" />
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>
{% endblock page %} {% block javascripts %} {{ block.super }}
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row').formset({
        addText: 'Add option',
        deleteText: 'Remove',
        prefix: 'option_set'
    });
    styleOptions();


    var btn = $(".add-row");
    btn.data("funcToCall", btn.attr("onclick"));
    $(".add-row").removeAttr("onclick");
    $(".add-row").bind("click", function (e) {
        var func = $(this).data("funcToCall");
        eval(func);
        styleOptions();

    })


    function styleOptions() {
        $('.table > tbody  > tr > td > select').addClass("form-control");
        $('.table > tbody  > tr > td > input').addClass("form-control");
    }
    
    var queryStr = window.location.pathname;
    var url_split = queryStr.split('/');
    var questionnaire_id = url_split[3];
    $('#id_questionnaire').val(questionnaire_id)
    //$('#id_nested_child_questions-TOTAL_FORMS').val(0)

</script> {% endblock javascripts %}

apps/surveys/templates/surveys/add_questionnaire.html
{% extends "tables.html" %} 
{% block page %} 
{% block title %}  Add questionnaire {% endblock title %}

<p class="text-muted font-13 m-b-30">
    
</p>

{% load crispy_forms_tags %} {% include 'messages.html' %}
<form method="post" class="bootstrap3" enctype="multipart/form-data">
    {% csrf_token %} 
        {{ questionnaire_form | crispy }}
 
    <div class="pull-right">
        <input class="btn btn-link" type="button" value="Cancel" onclick="window.history.go(-1);" />
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

{% endblock page %} 

apps/surveys/templates/surveys/enumerator.html
{% extends "page.html" %}
{% block title %} Enumerator Details{% endblock title %}

{% block page %}
    {% load crispy_forms_tags %}
    {% include 'messages.html' %}
    <form method="post" class="bootstrap3" enctype="multipart/form-data">
      {% csrf_token %} {{ form|crispy }}
      <div class="pull-right">
        <input class="btn btn-link" type="button" value="Cancel" onclick="window.history.go(-1);" />        
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </form>
{% endblock page %}

{% block extended_js %}
  <script>
    $(function () {
      var dateOptions = {
        dateFormat: "dd-mm-yy",
        constrainInput: true,
        gotoCurrent: true,
        minDate: new Date()
      };
      $("#startDate").datepicker(dateOptions);
      $("#endDate").datepicker(dateOptions);
    });
  </script>
{% endblock extended_js %}

apps/surveys/templates/surveys/enumerator_deactivate.html
{% extends "page.html" %}
{% block title %} Deactivate Enumerator{% endblock title %}
{% block page %}
    <div class="card">
        <div class="card-content">
            <h3> {{enumerator.title}}</h3>
            <p> County : {{enumerator.region}}</p>
            <p> Started on: {{enumerator.start_date}}</p>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <input class="btn btn-link" type="button" value="Cancel" onclick="window.history.go(-1);" />
            <input class="btn btn-danger" type="submit" value="Yes, Deactivate!" />
        </form>
    </div>
{% endblock page %}

apps/surveys/templates/surveys/enumerator_list.html
{% extends "tables.html" %}
{% block page %}
{% block title %} Enumerators {% endblock title %}

<p class="text-muted font-13 m-b-30">
    Manage the list of enumerators here
</p>

<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Identity Number</th>
            <th>Phone Number</th>
            <th>County</th>
            <th>Sub County</th>
            <th>Active</th>
            <th class="dt-center"></th>
            <th class="dt-center"></th>
        </tr>
    </thead>
    <tbody>
        {% for enumerator in enumerators %}
        <tr>
            <td>{{ forloop.counter }} {{ enumerator.enumerators }} </td>
            <td>{{enumerator.title}}</td>
            <td>{{enumerator.identity_number}}</td>
            <td>{{enumerator.phone_number}}</td>
            <td>{{enumerator.region}}</td>
            <td>{{enumerator.sub_region}}</td>
            <td>{{enumerator.enumerator_tenant.enabled}}</td>
            <td class="last">
                <a style='color:green' href="{% url 'enumerator_update' enumerator.id %}">Edit</a>
            </td>
            <td class="last">
                <a style='color:red' href="{% url 'enumerator_deactivate' enumerator.id %}">Deactivate</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<br>
<br>
<a class="btn btn-primary btn-lg btn-block" href="{% url 'enumerator_create'%}" role="button">Create New Enumerator</a>
{% endblock page %} {% block extended_js %}
<script>
    $('#datatable-responsive').dataTable({
        columnDefs: [
            { targets: [4, 5], "orderable": false },
        ],
        dom: 'Bfrtip',
        buttons: [
            {
                text: 'Export PDF',
                title: 'List of Registered Enumerators',
                extend: 'pdfHtml5',
                download: 'string',
                exportOptions: {
                    columns: [0,1, 2, 3, 4, 5, 6]
                }
            },
            {
                text: 'Export EXCEL',
                title: 'List of Registered Enumerators',
                extend: 'excelHtml5',
                download: 'string',
                exportOptions: {
                    columns: [0, 1, 2, 3, 4, 5]
                }
            }
        ]
    });
</script> {% endblock extended_js %}

apps/surveys/templates/surveys/location_survey_details.html
<p id='seller_title'><span style="font-weight: bold; font-size: 1.1em;">Enumerator: </span>{{survey.enumerator.title}}<p>
        <p id='seller_email'><span style="font-weight: bold; font-size: 1.1em;">Consumer's Name: </span>{{survey.consumer.user.get_full_name}}</p>
        <p id='seller_phone'><span style="font-weight: bold; font-size: 1.1em;">County: </span>{{survey.consumer.user.region.title}}</p>
        <p id='seller_phone'><span style="font-weight: bold; font-size: 1.1em;">SubCounty: </span>{{survey.consumer.user.sub_region.title}}</p>
        <p id='seller_phone'><span style="font-weight: bold; font-size: 1.1em;">Date surveyed: </span>{{survey.created_on}}</p>
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
            View consumer Details
        </button>
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Consumer's Details</h4>
                    </div>
                    <div class="modal-body">
                        <table>
                            <tr>
                                <td>Name: </td>
                                <td>{{survey.consumer.user.get_full_name}}</td>
                            </tr>
                            <tr>
                                <td>IdNo: </td>
                                <td>{{survey.consumer.user.identity_number}}</td>
                            </tr>
                            <tr>
                                <td>Joined: </td>
                                <td>{{survey.consumer.user.created_date}}</td>
                            </tr>
                            <tr>
                                <td>Phone:  </td>
                                <td>{{survey.consumer.user.phone}}</td>
                            </tr>
                            <tr>
                                <td>Email: </td>
                                <td>{{survey.consumer.user.email}}</td>
                            </tr>
                            <tr>
                                <td>County: </td>
                                <td>{{survey.consumer.user.region.title}}</td>
                            </tr>
                            <tr>
                                <td>SubCounty: </td>
                                <td>{{survey.consumer.user.sub_region.title}}</td>
                            </tr>
                            <tr>
                                <td>Location: </td>
                                <td>{{survey.consumer.user.location.title}}</td>
                            </tr>
                            <tr>
                                <td>Village: </td>
                                <td>{{survey.consumer.user.village.title}}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

apps/surveys/templates/surveys/questionnaires.html
{% extends "tables.html" %} {% block page %} {% block title %} Questionnaires {% endblock title %}

<p class="text-muted font-13 m-b-30">
    View questionnaires here
</p>
<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>No.</th>
            <th>Title</th>
            <th>Pass Mark</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for questionnaire in questionnaires %}
        <tr> 
            <td>{{ forloop.counter }} {{ questionnaire.questionnaires }} </td>
            <td>{{questionnaire.title }}</td>
            <td>{{questionnaire.pass_mark}}</td>
            <td class="last">
                <a style='color:green' href="{% url 'questions' questionnaire.id %}">View Questions</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a class="btn btn-primary btn-lg btn-block" href="{% url 'create_questionnaire'%}" role="button">Add Questionnaire</a>
{% endblock page %} {% block extended_js %} {{ block.super}}
<script>
    $('#datatable-responsive').dataTable({
        columnDefs: [
            { targets: [4, 5], "orderable": false },
        ],
    });
</script> {% endblock extended_js %}